spring:
  application:
    name: character-bff-service

external-api:
  character-service:
    url: http://127.0.0.1
    port: 8000
  game-session-service:
    url: http://127.0.0.1
    port: 8090

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
jwt:
  secret: your-256-bit-secret
